server:
  port: 8091  # 서버가 실행될 포트 번호

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkos  # MySQL 데이터베이스 연결 URL
    username: root  # 데이터베이스 사용자 이름
    password: mysql904#  # 데이터베이스 사용자 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 드라이버 클래스 이름

  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/업데이트 설정 (개발: update/create, 배포: none 권장)
      show-sql: false   # SQL 로그 출력 설정 (true: 활성, false: 비활성)

  servlet:
    multipart:
      max-file-size: 100MB      # 업로드 가능한 파일의 최대 크기
      max-request-size: 100MB   # 전체 요청의 최대 크기

#mybatis:
#  # Mapper XML 파일의 경로 설정
#  mapper-locations: classpath:mappers/**/*.xml
#  # MyBatis 설정 파일의 경로 설정
#  config-location: classpath:config/mybatis-config.xml
