server:
  port: 8091  # 서버가 실행될 포트 번호

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkos  # MySQL 데이터베이스 연결 URL
    username: root  # 데이터베이스 사용자 이름
    password: mysql904#  # 데이터베이스 사용자 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 드라이버 클래스 이름

  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/업데이트 설정 (개발: update/create, 배포: none 권장)
      show-sql: false   # SQL 로그 출력 설정 (true: 활성, false: 비활성)

  servlet:
    multipart:
      max-file-size: 100MB      # 업로드 가능한 파일의 최대 크기
      max-request-size: 100MB   # 전체 요청의 최대 크기

  mail:
    host: smtp.gmail.com  # 메일 서버 호스트 (Gmail SMTP 서버)
    port: 587  # 메일 서버 포트 (Gmail은 587 포트 사용)
    username: buuzzer2@gmail.com  # 메일 계정 (보내는 사람 이메일)
    password: lqqcjaqzzekjaqjw  # 메일 계정의 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true  # SMTP 인증 활성화
          starttls:
            enable: true  # TLS 시작 (보안 연결)
            required: true  # TLS 필수
          connectiontimeout: 5000  # 연결 시간 초과 (밀리초)
          timeout: 5000  # 읽기 시간 초과 (밀리초)
          writetimeout: 5000  # 쓰기 시간 초과 (밀리초)

  auth-code-expiration-millis: 1800000  # 인증 코드 만료 시간 (30분)
